### ISSUE TITLE
Previous site database file found on next storage if no database selected

### ISSUE THREAD

**Issue by devgiants** [devgiants/websites-backup#5]
On configuration like this 

```
 site1:
      database:
        server: localhost
        user: site1
        password: "123"
        name: site1
      files:
        root_dir: "/path/to/httpdocs/"
        include:
          - "shared/app/wp-content/uploads"
      backup_storages:
        - dropbox_site1

    site2:
      files:
        root_dir: "/path/to/httpdocs/"
        include:
          - "httpdocs"
      backup_storages:
        - dropbox_site2
```
The ste1 database archive is found on site1 storage, but also on site2 one (which doesn't have any database set for backup).
